version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/houdoku

    environment:
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout

      - run: sudo apt-get update && sudo apt-get install -y --no-install-recommends openjdk-8-jdk

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            - v1-dependencies-

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      - run:
          name: create package
          command: export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64 && mvn package

      - store_artifacts:
          path: out/artifacts/houdoku
