blank_issues_enabled: false
contact_links:
  - name: 🔮 Feature request 
    url: https://github.com/xgi/houdoku/discussions/new
    about: Request a new feature for Houdoku
  - name: 🤔 Question 
    url: https://github.com/xgi/houdoku/discussions/new
    about: Ask a question about Houdoku 
  - name: 🔗 Extensions repository
    url: https://github.com/xgi/houdoku-extensions/issues/new/choose
    about: Reports/requests for extensions should be opened in the extensions repository
  - name: 🖥️ Houdoku website
    url: https://houdoku.org
    about: Documentation for using Houdoku
