name: 🤔 Question
description: Ask a question about Houdoku
labels: [feature request]
body:
  - type: checkboxes
    id: acknowledgements
    attributes:
      label: Acknowledgements
      description: Before opening a ticket, please go through the following steps.
      options:
        - label: Check the documentation on [houdoku.org](https://houdoku.org).
          required: true
        - label: Check that there is not an existing ticket for this question, and that it is not related to an existing ticket.
          required: true
        - label: If you aren't sure whether something is a bug, create a bug report anyway (instead of using this form).
          required: true
        - label: Write a concise title for this ticket in the field above.
          required: true

  - type: checkboxes
    id: question-type
    attributes:
      label: Question type
      description: What is this question about?
      options:
        - label: Using Houdoku
          required: false
        - label: Clarification on existing documentation
          required: false
        - label: Development
          required: false
        - label: Other
          required: false

  - type: textarea
    id: question-details
    attributes:
      label: What is your question?
    validations:
      required: true

  - type: textarea
    id: additional-info
    attributes:
      label: Additional information
