name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  package:
    strategy:
      matrix:
        node: ['14']
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    name: Package (node ${{ matrix.node }}, ${{ matrix.os }})
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ matrix.node }}
      - run: yarn install
      - run: yarn package
        with:
          github_token: ${{ secrets.github_token }}
